from setuptools import setup, find_packages

setup(
    name='PETScope',
    version='0.1.0',
    packages=find_packages(),
    install_requires=[
        'antspyx==0.5.3',
        'click==8.1.7',
        'contourpy==1.3.0',
        'cycler==0.12.1',
        'joblib==1.4.2',
        'jsonpointer==2.1',
        'kiwisolver==1.4.7',
        'lxml==5.3.0',
        'matplotlib==3.9.2',
        'nibabel==5.2.1',
        'nilearn==0.10.4',
        'numpy==2.1.2',
        'openpyxl==3.1.5',
        'pandas==2.2.3',
        'patsy==0.5.6',
        'pillow==10.4.0',
        'pydicom==3.0.1',
        'pyparsing==3.1.4',
        'pytz==2024.2',
        'PyYAML==6.0.2',
        'scikit-learn==1.5.2',
        'scipy==1.14.1',
        'setuptools==72.1.0',
        'six==1.16.0',
        'statsmodels==0.14.4',
        'threadpoolctl==3.5.0',
        'tzdata==2024.2',
        'webcolors==24.8.0',
        'pytest==8.3.3',
        'pytest-dependency==0.6.0',
        'typer==0.12.5',
        'wheel==0.43.0',
    ],
    entry_points={
        'console_scripts': [
            'petscope = petscope.cli:app',  # Replace with the path to your Typer CLI
        ],
    },
    author='Stefan Radonjic',
    author_email='stefan.ai.research@gmail.com',
    description='A CLI toolbox for PET imaging analysis.',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/cepa995/PETScope',
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: Linux Ubuntu',
    ],
    python_requires='>=3.11',
)
